### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by Oluwatobilobaoke** [cornflourblue/node-mongo-signup-verification-api#1]
(node:35564) UnhandledPromiseRejectionWarning: Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:223:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
(node:35564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35564) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

While trying to register and also we need a readme file

**Comment by MoshinaT** [comment]
@Oluwatobilobaoke could you please let me know how did u merge it in front end part that was provided by @cornflourblue  earlier. I have commented the fake back end, but my calls are not hitting my local server 4000, and my db is not getting updated. It would be great if you can help me with this.  @cornflourblue kindly provide a read me file.

**Comment by cornflourblue** [comment]
Working on the blog post to go with this at the moment, shouldn't be too much longer

**Comment by Oluwatobilobaoke** [comment]
Okay, great Thanks.
@MoshinaT I didn't merge with frontend I was trying to build an API with auth then more functionalities that's just it.

@cornflourblue  We would like a post also merging the frontend with the backend the ones you made with fake backend wasn't that really self-explanatory.
Thank YOU.

**Comment by MoshinaT** [comment]
@Oluwatobilobaoke I have merged it, thanks. Just remove the fake back end part from front end, run your back end and then front. They work well. Thanks a lot @cornflourblue your work is very useful.

**Comment by cornflourblue** [comment]
Hey guys I've just finished the post to go with this repo, you can check it out at https://jasonwatmore.com/post/2020/05/13/node-mongo-api-with-email-sign-up-verification-authentication-forgot-password

Cheers,
Jason
