### ISSUE TITLE
Approach for removing expired refresh tokens

### ISSUE THREAD

**Issue by thedriveman** [cornflourblue/node-mongo-signup-verification-api#2]
@cornflourblue - terrific work on this! I'm going to use this boilerplate for my project. 

Question: In the current implementation, the refreshTokens array under the accounts collection grows indefinitely. To remove expired refresh tokens, my initial thought was to use mongoDB's [TTL Indexes](https://docs.mongodb.com/manual/tutorial/expire-data/), however, the TTL index scope is limited to documents, not to arrays within a document, per the current schema.

How would approach removal of expired tokens?

**Comment by cornflourblue** [comment]
Thanks @thedriveman - actually this issue occurred to me too after I'd added the refresh token functionality last week.

To get around it I've updated the mongoose models to store the refresh tokens in their own collection in MongoDB, so you will be able to use TTL Indexes.

Here's the commit with the changes - https://github.com/cornflourblue/node-mongo-signup-verification-api/commit/80c0226a39b357685a7f86582d5e26afed671297

Cheers,
Jason
